env: "local"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s 
database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "postgres"
  ssl_mode: "disable"
  timeout: 5s